=== Ahoo-Wang/CoSec/document/cosec-policy.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "https://github.com/Ahoo-Wang/CoSec/blob/main/document/cosec-policy.schema.json",
  "title": "CoSec Policy Schema",
  "type": "object",
  "properties": {
    "id": {
      "description": "The id of the policy",
      "type": "string"
    },
    "category": {
      "description": "The category of the policy",
      "type": "string"
    },
    "name": {
      "description": "The name of the policy",
      "type": "string"
    },
    "description": {
      "description": "The description of the policy",
      "type": "string"
    },
    "tenantId": {
      "description": "The tenantId of the policy",
      "type": "string"
    },
    "type": {
      "description": "The type of the policy",
      "$ref": "#/definitions/policyType"
    },
    "statements": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/statement"
      }
    }
  },
  "required": [
    "category",
    "name",
    "description",
    "tenantId",
    "type",
    "statements"
  ],
  "definitions": {
    "policyType": {
      "enum": [
        "global",
        "system",
        "custom"
      ]
    },
    "effect": {
      "enum": [
        "allow",
        "deny"
      ]
    },
    "actionType": {
      "enum": [
        "all",
        "none",
        "path",
        "reg"
      ]
    },
    "conditionType": {
      "enum": [
        "all",
        "none",
        "authenticated",
        "in_default_tenant",
        "in_platform_tenant",
        "in_user_tenant",
        "in_ip",
        "reg_ip",
        "spel",
        "ognl"
      ]
    },
    "requestPart": {
      "enum": [
        "action",
        "tenantId",
        "remoteIp",
        "origin",
        "referer"
      ]
    },
    "actionMatcher": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "properties": {
        "type": {
          "anyOf": [
            {
              "$ref": "#/definitions/actionType"
            },
            {
              "type": "string"
            }
          ]
        },
        "pattern": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    },
    "conditionMatcher": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      },
      "properties": {
        "type": {
          "anyOf": [
            {
              "$ref": "#/definitions/conditionType"
            },
            {
              "type": "string"
            }
          ]
        },
        "pattern": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    },
    "statement": {
      "type": "object",
      "properties": {
        "effect": {
          "$ref": "#/definitions/effect"
        },
        "actions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/actionMatcher"
          }
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/conditionMatcher"
          }
        }
      }
    }
  }
}

=== Ahoo-Wang/CoSec/cosec-gateway-server/src/main/resources/cosec-policy/health-probe-policy.json
{
  "id": "(health-probe)",
  "name": "健康探针",
  "category": "health-probe",
  "description": "健康探针全局策略",
  "type": "global",
  "tenantId": "(platform)",
  "statements": [
    {
      "name": "actuator",
      "action": [
        "/actuator/health",
        "/actuator/health/readiness",
        "/actuator/health/liveness"
      ]
    }
  ]
}
