=== Ahoo-Wang/CoSec/schema/cosec-policy.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "$id": "https://github.com/Ahoo-Wang/CoSec/blob/main/schema/cosec-policy.schema.json",
  "title": "CoSec Policy Schema",
  "type": "object",
  "properties": {
    "id": {
      "description": "The id of the policy",
      "type": "string"
    },
    "category": {
      "description": "The category of the policy",
      "type": "string"
    },
    "name": {
      "description": "The name of the policy",
      "type": "string"
    },
    "description": {
      "description": "The description of the policy",
      "type": "string"
    },
    "tenantId": {
      "description": "The tenantId of the policy",
      "type": "string"
    },
    "type": {
      "description": "The type of the policy",
      "$ref": "#/definitions/policyType"
    },
    "condition": {
      "description": "The condition of the policy",
      "$ref": "condition.schema.json"
    },
    "statements": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/statement"
      }
    }
  },
  "required": [
    "category",
    "name",
    "description",
    "tenantId",
    "type",
    "statements"
  ],
  "definitions": {
    "policyType": {
      "enum": [
        "global",
        "system",
        "custom"
      ]
    },
    "effect": {
      "$ref": "definitions.schema.json#/definitions/effect",
      "default": "allow"
    },
    "statement": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the Statement",
          "type": "string"
        },
        "effect": {
          "$ref": "#/definitions/effect",
          "default": "allow"
        },
        "action": {
          "$ref": "action.schema.json"
        },
        "condition": {
          "$ref": "condition.schema.json"
        }
      },
      "required": [
        "action"
      ]
    }
  }
}

=== Ahoo-Wang/CoSec/cosec-core/src/test/resources/cosec-policy/test-policy.json
{
  "id": "id",
  "name": "name",
  "category": "category",
  "description": "description",
  "type": "global",
  "tenantId": "tenantId",
  "condition": {
    "bool": {
      "and": [
        {
          "authenticated": {}
        },
        {
          "rateLimiter": {
            "permitsPerSecond": 10
          }
        }
      ]
    }
  },
  "statements": [
    {
      "action": {
        "path": {
          "pattern": "/user/#{principal.id}/*",
          "options": {
            "caseSensitive": false,
            "separator": "/",
            "decodeAndParseSegments": false
          }
        }
      }
    },
    {
      "name": "Anonymous",
      "action": [
        "/auth/register",
        "/auth/login"
      ]
    },
    {
      "name": "UserScope",
      "action": "/user/#{principal.id}/*",
      "condition": {
        "authenticated": {}
      }
    },
    {
      "name": "Developer",
      "action": "*",
      "condition": {
        "in": {
          "part": "context.principal.id",
          "value": [
            "developerId"
          ]
        }
      }
    },
    {
      "name": "RequestOriginDeny",
      "effect": "deny",
      "action": "*",
      "condition": {
        "regular": {
          "negate": true,
          "part": "request.origin",
          "pattern": "^(http|https)://github.com"
        }
      }
    },
    {
      "name": "IpBlacklist",
      "effect": "deny",
      "action": "*",
      "condition": {
        "path": {
          "part": "request.remoteIp",
          "pattern": "192.168.0.*",
          "options": {
            "caseSensitive": false,
            "separator": ".",
            "decodeAndParseSegments": false
          }
        }
      }
    },
    {
      "name": "RegionWhitelist",
      "effect": "deny",
      "action": "*",
      "condition": {
        "regular": {
          "negate": true,
          "part": "request.attributes.ipRegion",
          "pattern": "^中国\\|0\\|(上海|广东省)\\|.*"
        }
      }
    },
    {
      "name": "AllowDeveloperOrIpRange",
      "action": "*",
      "condition": {
        "bool": {
          "and": [
            {
              "authenticated": {}
            }
          ],
          "or": [
            {
              "in": {
                "part": "context.principal.id",
                "value": [
                  "developerId"
                ]
              }
            },
            {
              "path": {
                "part": "request.remoteIp",
                "pattern": "192.168.0.*",
                "options": {
                  "caseSensitive": false,
                  "separator": ".",
                  "decodeAndParseSegments": false
                }
              }
            }
          ]
        }
      }
    },
    {
      "name": "TestContains",
      "effect": "allow",
      "action": "*",
      "condition": {
        "contains": {
          "part": "request.attributes.ipRegion",
          "value": "上海"
        }
      }
    },
    {
      "name": "TestStartsWith",
      "effect": "allow",
      "action": "*",
      "condition": {
        "startsWith": {
          "part": "request.attributes.ipRegion",
          "value": "中国"
        }
      }
    },
    {
      "name": "TestEndsWith",
      "effect": "allow",
      "action": {
        "all": {
          "method": "GET"
        }
      },
      "condition": {
        "endsWith": {
          "part": "request.attributes.remoteIp",
          "value": ".168.0.1"
        }
      }
    },
    {
      "name": "TestActionObject",
      "effect": "allow",
      "action": {
        "path": {
          "method": "GET",
          "pattern": [
            "/user/#{principal.id}/*"
          ],
          "options": {
            "caseSensitive": false,
            "separator": "/",
            "decodeAndParseSegments": false
          }
        }
      }
    },
    {
      "name": "TestActionObjectMultiPattern",
      "effect": "allow",
      "action": {
        "path": {
          "method": [
            "GET",
            "POST"
          ],
          "pattern": [
            "/user/#{principal.id}/*",
            "/user/#{principal.id}/order/*"
          ],
          "options": {
            "caseSensitive": false,
            "separator": "/",
            "decodeAndParseSegments": false
          }
        }
      }
    },
    {
      "name": "TestComposite",
      "effect": "allow",
      "action": {
        "composite": [
          "/user/#{principal.id}/*",
          {
            "path": {
              "method": "POST",
              "pattern": [
                "/user/#{principal.id}/order/*"
              ]
            }
          }
        ]
      }
    },
    {
      "name": "TestInRole",
      "effect": "allow",
      "action": "*",
      "condition": {
        "inRole": {
          "value": "admin"
        }
      }
    },
    {
      "name": "RequestPathVar",
      "action": "/user/{id}",
      "condition": {
        "eq": {
          "part": "request.path.var.id",
          "value": "userId"
        }
      }
    },
    {
      "name": "RequestPathVarTemplate",
      "action": "/user/{id}",
      "condition": {
        "eq": {
          "part": "request.path.var.id",
          "value": "#{principal.id}"
        }
      }
    },
    {
      "name": "compositeAction",
      "action": {
        "composite": [
          {
            "path": {
              "pattern": "/user/#{principal.id}/*"
            }
          },
          {
            "path": {
              "pattern": "/user/#{principal.id}/order/*"
            }
          }
        ]
      }
    },
    {
      "name": "arrayAction",
      "action": [
        "/user/#{principal.id}/*",
        {
          "path": {
            "pattern": "/user/#{principal.id}/*"
          }
        },
        {
          "path": {
            "pattern": "/user/#{principal.id}/order/*"
          }
        }
      ]
    }
  ]
}

=== Ahoo-Wang/CoSec/cosec-core/src/test/resources/test-policy.json
{
  "id": "id",
  "name": "name",
  "category": "category",
  "description": "description",
  "type": "global",
  "tenantId": "tenantId",
  "condition": {
    "bool": {
      "and": [
        {
          "authenticated": {}
        },
        {
          "rateLimiter": {
            "permitsPerSecond": 10
          }
        }
      ]
    }
  },
  "statements": [
    {
      "action": {
        "path": {
          "pattern": "/user/#{principal.id}/*",
          "options": {
            "caseSensitive": false,
            "separator": "/",
            "decodeAndParseSegments": false
          }
        }
      }
    },
    {
      "name": "Anonymous",
      "action": [
        "/auth/register",
        "/auth/login"
      ]
    },
    {
      "name": "UserScope",
      "action": "/user/#{principal.id}/*",
      "condition": {
        "authenticated": {}
      }
    },
    {
      "name": "Developer",
      "action": "*",
      "condition": {
        "in": {
          "part": "context.principal.id",
          "value": [
            "developerId"
          ]
        }
      }
    },
    {
      "name": "RequestOriginDeny",
      "effect": "deny",
      "action": "*",
      "condition": {
        "regular": {
          "negate": true,
          "part": "request.origin",
          "pattern": "^(http|https)://github.com"
        }
      }
    },
    {
      "name": "IpBlacklist",
      "effect": "deny",
      "action": "*",
      "condition": {
        "path": {
          "part": "request.remoteIp",
          "pattern": "192.168.0.*",
          "options": {
            "caseSensitive": false,
            "separator": ".",
            "decodeAndParseSegments": false
          }
        }
      }
    },
    {
      "name": "RegionWhitelist",
      "effect": "deny",
      "action": "*",
      "condition": {
        "regular": {
          "negate": true,
          "part": "request.attributes.ipRegion",
          "pattern": "^中国\\|0\\|(上海|广东省)\\|.*"
        }
      }
    },
    {
      "name": "AllowDeveloperOrIpRange",
      "action": "*",
      "condition": {
        "bool": {
          "and": [
            {
              "authenticated": {}
            }
          ],
          "or": [
            {
              "in": {
                "part": "context.principal.id",
                "value": [
                  "developerId"
                ]
              }
            },
            {
              "path": {
                "part": "request.remoteIp",
                "pattern": "192.168.0.*",
                "options": {
                  "caseSensitive": false,
                  "separator": ".",
                  "decodeAndParseSegments": false
                }
              }
            }
          ]
        }
      }
    },
    {
      "name": "TestContains",
      "effect": "allow",
      "action": "*",
      "condition": {
        "contains": {
          "part": "request.attributes.ipRegion",
          "value": "上海"
        }
      }
    },
    {
      "name": "TestStartsWith",
      "effect": "allow",
      "action": "*",
      "condition": {
        "startsWith": {
          "part": "request.attributes.ipRegion",
          "value": "中国"
        }
      }
    },
    {
      "name": "TestEndsWith",
      "effect": "allow",
      "action": "*",
      "condition": {
        "endsWith": {
          "part": "request.attributes.remoteIp",
          "value": ".168.0.1"
        }
      }
    }
  ]
}
